export const NETWORK_CONNECTED = "NETWORK_CONNECTED";
export const RESET_STORE = "RESET_STORE";

export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_ALL_STORE_LIST = "GET_ALL_STORE_LIST";
export const GET_ALL_STORE_LIST_BY_ALPHA = "GET_ALL_STORE_LIST_BY_ALPHA";
