export const asyncKey = {
  USER_TOKEN: "USER_TOKEN",
  USER_TOKEN_DATA: "USER_TOKEN_DATA",
  USER_DETAILS: "USER_DETAILS",
  USER_PHONE: "USER_PHONE",
  KEEP_ME_LOGGED_IN: "KEEP_ME_LOGGED_IN",
  CLIENT_SECRET: "CLIENT_SECRET",
};
