export const asyncKeys = {
  IS_INTRO: 'IS_INTRO',
  IS_LOGGED_IN: 'IS_LOGGED_IN',
  USER_DATA: 'USER_DATA',
  USER_TOKEN: 'USER_TOKEN',
  PUSH_TOKEN: 'PUSH_TOKEN',
  REMEMBER_ME: 'REMEMBER_ME',
  LANGUAGE: 'LANGUAGE',
  USER_TYPE: 'USER_TYPE',
};
