export const asyncKey = {
  USER_TOKEN: "USER_TOKEN",
  USER_TOKEN_DATA: "USER_TOKEN_DATA",
  USER_DETAILS: "USER_DETAILS",
  USER_PHONE: "USER_PHONE",
  KEEP_ME_LOGGED_IN: "KEEP_ME_LOGGED_IN",
  CLIENT_SECRET: "CLIENT_SECRET",
  DELETED_CAMPAIGN: "DELETED_CAMPAIGN",
  BOOKMARK_CAMPAIGN: "BOOKMARK_CAMPAIGN",
  IN_APP_NOTIFICATIONS: "IN_APP_NOTIFICATIONS",
};
